name: Build with Gradle

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Build'
        required: true
        default: 'Build'
      home:
        description: 'location'
        required: false
        
jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Wrap with Gradle
      run: ./gradlew wrapper --gradle-version=6.8.2 --distribution-type=bin
    - name: Dep with Gradle
      run: ./gradlew dependencies
    - name: Test with Gradle
      run: ./gradlew test
    - name: Build with Gradle
      run: ./gradlew release
      
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      if: success()
      with:
          name: React
          path: release\6.646\React-6.646.jar
    - name: Archive artifacts 2
      uses: actions/upload-artifact@v2
      if: success()
      with:
          name: React 3
          path: React\release\6.646\React-6.646.jar
    - name: Archive artifacts 2
      uses: actions/upload-artifact@v2
      if: success()
      with:
          name: React 3
          path: \home\runner\work\React\React\release\6.646\React-6.646.jar
